### ISSUE TITLE
docs: ReadMe could explain basic usage of these types

### ISSUE THREAD

**Issue by TravisL12** [lokshunhung/pokeapi-types#343]
First off this thank you so much for doing this!

I had to dig into the repo a bit to figure out how to utilize the types though.

```
import { PokeAPI } from "pokeapi-types";

PokeAPI.Pokemon // reference Pokemon Species
... // add the other exported types?
```

**Comment by lokshunhung** [comment]
Hi @TravisL12, thank you for the interest of this package.

I updated the readme with an example. Hope it helps :)
